version: "3"

services:
  nginx:
    image: nginx
    restart: ${RESTART}
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./frontend/dist:/var/www/public
      - ./uploads:/var/www/downloads
      - ./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    image: node
    restart: ${RESTART}
    ports:
      - ${BACKEND_DEBUG_PORT}:9229
    depends_on:
      - mongo
    volumes:
      - ./backend:/var/www/backend
      - ./uploads:/var/www/uploads
    working_dir: /var/www/backend
    environment:
      - NODE_ENV=development
      - MONGO_HOST=${MONGO_CONNECT_HOST}
      - MONGO_PORT=${MONGO_CONNECT_PORT}
      - MONGO_DB=botoshop
      - BASE_DOWNLOAD_URL=${BASE_DOWNLOAD_URL}
      - UPLOAD_DIR=/var/www/uploads
      - BOT_HTTP_INTERFACE_URL=${BOT_HTTP_INTERFACE_URL}
      - YOO_SHOP_ID=${YOO_SHOP_ID}
      - YOO_SECRET_KEY=${YOO_SECRET_KEY}
      - YOO_TEST=${YOO_TEST}
    command: npm run start

  bot:
    image: node
    restart: ${RESTART}
    ports:
      - ${BOT_HTTP_PORT}:3000
      - ${BOT_DEBUG_PORT}:9229
    depends_on:
      - mongo
    volumes:
      - ./bot:/var/bot
      - ./uploads:/var/www/uploads
    working_dir: /var/bot
    environment:
      - NODE_ENV=development
      - MONGO_HOST=mongo
      - MONGO_DB=botoshop
      - MAILINGS_CHECK_INTERVAL_SEC=${MAILINGS_CHECK_INTERVAL_SEC}
      - PAYMENT_CHECK_INTERVAL_SEC=${PAYMENT_CHECK_INTERVAL_SEC}
      - PAYMENT_STATUS_CHECK_INTERVAL_SEC=${PAYMENT_STATUS_CHECK_INTERVAL_SEC}
      - TEST_USER_ID=${TEST_USER_ID}
      - TEST_CHAT_ID=${TEST_CHAT_ID}
      - TEST_QUEUE_SIZE=${TEST_QUEUE_SIZE}
      - START_DELAY_SECONDS=${START_DELAY_SECONDS}
      - TGAPI_ROOT=${TGAPI_ROOT}
      - UPLOAD_DIR=/var/www/uploads
      - YOO_SHOP_ID=${YOO_SHOP_ID}
      - YOO_SECRET_KEY=${YOO_SECRET_KEY}
      - YOO_TEST=${YOO_TEST}
    command: npm run start

  mongo:
    image: mongo
    restart: ${RESTART}
    volumes:
      - ./etc/database:/data/db
    ports:
      - ${MONGO_PORT}:27017