version: "3"

services:
  nginx:
    image: nginx
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./frontend/dist:/var/www/public
      - ./uploads:/var/www/downloads
      - ./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    image: node
    ports:
      - ${BACKEND_DEBUG_PORT}:9229
    depends_on:
      - mongo
    volumes:
      - ./backend:/var/www/backend
      - ./uploads:/var/www/uploads
    working_dir: /var/www/backend
    environment:
      - NODE_ENV=development
      - MONGO_HOST=mongo
      - MONGO_DB=funnel_bot
      - BASE_DOWNLOAD_URL=http://localhost:8196/download/
      - UPLOAD_DIR=/var/www/uploads
    command: npm run start

  bot:
    image: node
    ports:
      - ${BOT_DEBUG_PORT}:9229
    depends_on:
      - mongo
    volumes:
      - ./bot:/var/bot
    working_dir: /var/bot
    environment:
      - NODE_ENV=development
      - MONGO_HOST=mongo
      - MONGO_DB=funnel_bot
      - MAILINGS_CHECK_INTERVAL_SEC=${MAILINGS_CHECK_INTERVAL_SEC}
      - PAYMENT_CHECK_INTERVAL_SEC=${PAYMENT_CHECK_INTERVAL_SEC}
      - PAYMENT_STATUS_CHECK_INTERVAL_SEC=${PAYMENT_STATUS_CHECK_INTERVAL_SEC}
      - TEST_USER_ID=${TEST_USER_ID}
      - TEST_CHAT_ID=${TEST_CHAT_ID}
      - TEST_QUEUE_SIZE=${TEST_QUEUE_SIZE}
      - START_DELAY_SECONDS=${START_DELAY_SECONDS}
      - TGAPI_ROOT=${TGAPI_ROOT}
    command: npm run start

  mongo:
    image: mongo
    volumes:
      - ./etc/database:/data/db
    ports:
      - ${MONGO_PORT}:27017