POST http://localhost:8196/api/export/stages
Content-Type: application/json

{
  "stages": {}
}

###

POST http://localhost:8196/api/export/stages
Content-Type: application/json

{
  "stages": {
    "groupDays": true
  }
}

###

POST http://localhost:8196/api/export/buttons
Content-Type: application/json

{
  "buttons": {}
}

###

POST http://localhost:8196/api/export/buttons
Content-Type: application/json

{
  "buttons": {
    "groupDays": true
  }
}

###

POST http://localhost:8196/api/export/refs
Content-Type: application/json

{
  "refs": {}
}

###

POST http://localhost:8196/api/export/stages
Content-Type: application/json

{
  "stages": {
    "funnels": [
      "w614z07a0",
      "Ty0do6YMn"
    ],
    "start": 1615842000,
    "end": 1616101199,
    "groupDays": true
  }
}

###